# Generated by Django 3.2.4 on 2021-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.TextField(max_length=255)),
                ('music_name', models.TextField(max_length=255)),
                ('music_id', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Musiqa',
                'verbose_name_plural': 'Musiqalar',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Userlar',
            },
        ),
    ]
