# Generated by Django 3.2.6 on 2021-08-09 08:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_auto_20210718_2308'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='musics',
            managers=[
                ('music', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
