# Generated by Django 3.2.6 on 2021-08-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_auto_20210810_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='uu_id',
            new_name='u_id',
        ),
    ]
