# Generated by Django 3.2.6 on 2021-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_rename_uu_id_users_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='u_id',
            field=models.TextField(max_length=15),
        ),
    ]
