# Generated by Django 3.2.6 on 2021-08-10 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_alter_users_u_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botapp.users')),
            ],
        ),
    ]
