# Generated by Django 3.2.6 on 2021-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_send_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('s', 'Send Message')], default=23, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Send_Message',
        ),
    ]
