# Generated by Django 3.2.6 on 2021-08-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0013_auto_20210820_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmanager',
            old_name='types',
            new_name='txt',
        ),
    ]
