# Generated by Django 3.2.6 on 2021-08-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0016_auto_20210822_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='photo',
            field=models.ImageField(upload_to='bot/'),
        ),
    ]
