# Generated by Django 3.2.6 on 2021-08-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0018_alter_taskmanager_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
