# Generated by Django 3.2.6 on 2021-08-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0019_alter_taskmanager_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
